### PR TITLE
Handling string dtype

### PR DESCRIPTION
**Pull request by lucmehl**
modified var creation for incomplete profiles.

it looks like this branch is on an old fork (50 commits behind master). if it is more efficient i can make a new fork and make my changes again. let me know.

### CODE REVIEW

**Comment by lucmehl** [comment]
@kwilcox sorry, can't figure out how to assign this review to you.

**Comment by lucmehl** [comment]
i synced the lucmehl fork to master.

**Comment by kwilcox** [comment]
Ah so the issue here is if the first profile is all `NaN` or a number, future profiles will need to map to that type since the netCDF variable is created based on the data on the first profile. You changed it so the netCDF variables are created at the full dataframe level. Cool, that makes sense. I'll have to port this to the other feature types.

Can you fix up the paths in the tests?

**Comment by lucmehl** [comment]
I will try to work on the tests with Jessica.

I think a similar correction needs to be made at the dimension level. Trevor ran into this with profile ids of mixed datatypes... pocean say int first, assigned the dim with int, and then errored on subsequent non-int.

**Comment by lucmehl** [comment]
I updated the test file path, not sure if it will work for you.

**Comment by kwilcox** [comment]
https://github.com/pyoceans/pocean-core/pull/53

**Pull request closed without merging**
