### PR TITLE
Implemented OrthogonalMultidimensionalTimeseriesProfile

### PR DESCRIPTION
**Pull request by joefutrelle**

### CODE REVIEW

**Comment by kwilcox** [comment]
Won't be able to review until tonight. Can you wait? If you didn't know you can install the local code as a package with `pip install -e [path to pocean code root]`

**Comment by joefutrelle** [comment]
No hurry, in the meantime here's a gist demonstrating DataFrame roudntripping

https://gist.github.com/joefutrelle/b80633f5b2e60df180aa115512babd6a

**Comment by joefutrelle** [comment]
I think that there's an issue with this where I'm conflating "z" and whatever variable is dimensioned to the profiler levels, which might be e.g., pressure and not z which might be stored in one of the multidimensional obs variables. I think the solution is to call the level variable something like "level" in the incoming and outgoing dataframe and not set axis=Z on it. Does that make sense?

My preference is just to leave this PR open while I address this issue.

**Comment by joefutrelle** [comment]
Now that some time has passed my pref is to merge this first and deal with the issue in a separate PR

**Comment by kwilcox** [comment]
@joefutrelle Is this still ready for review?

**Comment by joefutrelle** [comment]
The issue that I brought up upthread still applies, and I'm wondering what your opinion is about that. If it's appropriate to call pressure "z", then I think it's fine as is. I think `to_dataframe` is probably not generic enough to handle arbitrary CF timeseriesProfile files, but that's an implementation issue and not an API issue, so I don't think that should hold up merging.

**Comment by rsignell-usgs** [comment]
As @ocefpaf reminded me, depth technically depends on pressure and latitude
https://github.com/pyoceans/python-seawater/blob/4fb8d92d44a2760114a3a7accf5ba1b2504f7dda/seawater/test/seawater_v3_3/sw_dpth.m#L9-L20

**Comment by rsignell-usgs** [comment]
But if this is just for alerts and alarms for engineering data, it would be fine to treat as depth.

**Comment by rsignell-usgs** [comment]
@cwingard or @crisien ,care to weigh in here?

**Comment by cwingard** [comment]
For general purposes (initial data plotting, qa/qc, etc), pressure can be considered the same as depth. If I was making a final dataset available to other users or completing a more formal analysis, I would convert pressure to depth. Otherwise, as Rich indicated, its fine to set the Z axis to pressure for alerts/alarms/etc.

**Comment by rsignell-usgs** [comment]
Sounds like a go then!    @kwilcox do you want accept the PR and cut 1.0?

**Pull request merged**
