### PR TITLE
Some improvements to attribute generation (try2)

### PR DESCRIPTION
**Pull request by eldobbins**
Added comments to describe usage
Added POINT geography for timeseries (i.e. moorings)
Added functions to the init so can access them.

Will these eventually be called by the netCDF generation functions rather than accessible via users?

### CODE REVIEW

**Comment by eldobbins** [comment]
Travis didn't like something with Python 2.7 that works with Python3.  Specifically, a type cast:

> >       miny = round(df[axes.y].min(), 6).astype('float')
> E       AttributeError: 'float' object has no attribute 'astype'
> 

That's in both geospatial and vertical.
Fixing

**Comment by kwilcox** [comment]
I can't get the same errors locally using py2.7, poking at this. I understand why `.astype(float)` wouldn't work with a `float`, but that should be a numpy scalar at that point in both 2.7 and 3+.

**Comment by kwilcox** [comment]
OK got it to fail, sent you a ping on hangouts to discuss!

**Comment by eldobbins** [comment]
Added the wrapper function and switched round(float.

**Pull request merged**
